-- Role: sa
-- DROP ROLE IF EXISTS sa;

CREATE ROLE sa WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:iwfXl7X2SLATROLwcqXanQ==$B4Wr0qi0/b+NXLOukxuELRAt4ULUxYgs4v7/cuWisCM=:rLgRiRfzqrET+2TtxxErqQGfRRCnwkLN6E4LysuT3lI=';